# Generated by Django 4.2 on 2023-04-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image_link',
            field=models.CharField(default=0, max_length=2000),
            preserve_default=False,
        ),
    ]
